#!/usr/bin/env python3
"""Backup Langfuse LLM-as-a-Judge evaluator configurations.

This script backs up all Langfuse configurations used for LLM-as-a-Judge evaluation:
1. Score Configs - Define score types, ranges, and metadata
2. Prompts - Langfuse prompts that may be used by evaluators
3. Evaluator Documentation - Documents which Python evaluators are used and their parameters

Note: The actual evaluator functions are Python code (in app/shared/services/g_eval/),
      not stored in Langfuse. This backup captures the Langfuse-side configuration.

Usage:
    poetry run python scripts/backup_langfuse_evaluators.py

Environment Variables:
    LANGFUSE_PUBLIC_KEY: Langfuse public API key
    LANGFUSE_SECRET_KEY: Langfuse secret API key
    LANGFUSE_HOST: Langfuse server URL (default: http://localhost:3000)

Output:
    backend/data/langfuse_evaluators_backup.json
"""

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import httpx
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()


def get_langfuse_credentials() -> tuple[str, str, str]:
    """Get Langfuse credentials from environment variables.

    Returns:
        Tuple of (public_key, secret_key, host)

    Raises:
        SystemExit: If credentials are not configured

    """
    public_key = os.getenv("LANGFUSE_PUBLIC_KEY")
    secret_key = os.getenv("LANGFUSE_SECRET_KEY")
    host = os.getenv("LANGFUSE_HOST", "http://localhost:3000")

    if not public_key or not secret_key:
        print("Error: Langfuse credentials not configured")
        print("Required environment variables:")
        print("  - LANGFUSE_PUBLIC_KEY")
        print("  - LANGFUSE_SECRET_KEY")
        print("  - LANGFUSE_HOST (optional, default: http://localhost:3000)")
        sys.exit(1)

    return public_key, secret_key, host


async def fetch_score_configs(client: httpx.AsyncClient, host: str) -> list[dict]:
    """Fetch all score configurations from Langfuse.

    Score configs define the types and ranges of scores used by evaluators.

    Args:
        client: Configured HTTP client with auth
        host: Langfuse server URL

    Returns:
        List of score configurations

    """
    url = f"{host}/api/public/score-configs"

    print(f"Fetching score configurations from {url}...")

    response = await client.get(url)
    response.raise_for_status()

    data = response.json()

    # The response should contain a list of score configs
    # Structure: {"data": [...], "meta": {...}}
    score_configs = data.get("data", [])

    print(f"Found {len(score_configs)} score configurations")

    # Filter for G-Eval related configs
    g_eval_configs = [c for c in score_configs if c["name"].startswith("g_eval_")]
    print(f"  - {len(g_eval_configs)} G-Eval score configs")

    return score_configs


async def fetch_prompts(client: httpx.AsyncClient, host: str) -> list[dict]:
    """Fetch all prompts from Langfuse.

    Many evaluators reference prompts, so we backup those too.

    Args:
        client: Configured HTTP client with auth
        host: Langfuse server URL

    Returns:
        List of prompt configurations

    """
    url = f"{host}/api/public/v2/prompts"

    print(f"\nFetching prompt configurations from {url}...")

    response = await client.get(url, params={"limit": 100})
    response.raise_for_status()

    data = response.json()
    prompts = data.get("data", [])

    print(f"Found {len(prompts)} prompt configurations")

    return prompts


def document_evaluator_functions() -> dict:
    """Document the Python evaluator functions used in experiments.

    Returns:
        Dictionary documenting evaluator functions and their configurations

    """
    return {
        "note": "Evaluator functions are Python code, not stored in Langfuse",
        "source_files": [
            "app/shared/services/g_eval/langfuse_evaluators.py",
            "app/shared/services/g_eval/rubrics.py",
            "app/shared/services/g_eval/scorer.py",
        ],
        "standard_evaluators": {
            "description": "Generated by get_standard_evaluators(agent_type)",
            "criteria": ["completeness", "accuracy", "coherence", "depth"],
            "score_names": [
                "g_eval_completeness",
                "g_eval_accuracy",
                "g_eval_coherence",
                "g_eval_depth",
                "g_eval_overall",
            ],
        },
        "run_evaluators": {
            "description": "Generated by get_standard_run_evaluators()",
            "evaluators": [
                {
                    "name": "average_g_eval_score_evaluator",
                    "output_score": "avg_g_eval_overall",
                    "description": "Calculates average G-Eval overall score across all items",
                },
                {
                    "name": "criterion_average_evaluator",
                    "output_scores": [
                        "avg_g_eval_completeness",
                        "avg_g_eval_accuracy",
                        "avg_g_eval_coherence",
                        "avg_g_eval_depth",
                    ],
                    "description": "Calculates average per criterion",
                },
                {
                    "name": "quality_threshold_evaluator",
                    "output_score": "quality_pass_rate",
                    "default_threshold": 0.6,
                    "description": "Counts items passing quality threshold",
                },
            ],
        },
        "agent_types": [
            "tech_comparator",
            "security_auditor",
            "implementation_planner",
            "integration_analyst",
            "performance_profiler",
            "code_reviewer",
            "documentation_specialist",
            "test_strategist",
        ],
        "llm_model": "gemini-2.5-flash",
        "llm_model_note": "Configured in backend/.env as LLM_MODEL",
    }


def save_backup(
    score_configs: list[dict],
    prompts: list[dict],
    evaluator_docs: dict,
    output_path: Path,
) -> None:
    """Save evaluator and prompt configurations to JSON backup file.

    Args:
        score_configs: List of score configurations
        prompts: List of prompt configurations
        evaluator_docs: Documentation of evaluator functions
        output_path: Path to save backup file

    """
    backup_data = {
        "metadata": {
            "backup_timestamp": datetime.now(timezone.utc).isoformat(),
            "score_config_count": len(score_configs),
            "prompt_count": len(prompts),
            "langfuse_host": os.getenv("LANGFUSE_HOST", "http://localhost:3000"),
            "description": (
                "Backup of Langfuse configurations for LLM-as-a-Judge evaluation. "
                "Score configs define score types/ranges. Prompts define evaluation prompts. "
                "Evaluator functions are Python code in app/shared/services/g_eval/."
            ),
        },
        "score_configs": score_configs,
        "prompts": prompts,
        "evaluator_functions": evaluator_docs,
    }

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Save to JSON file
    with output_path.open("w") as f:
        json.dump(backup_data, f, indent=2, default=str)

    print(f"\nBackup saved to {output_path}")
    print(f"  - {len(score_configs)} score configurations")
    print(f"  - {len(prompts)} prompt configurations")
    print(f"  - Evaluator function documentation")

    # Show summary of G-Eval configs
    g_eval_configs = [c for c in score_configs if c["name"].startswith("g_eval_")]
    if g_eval_configs:
        print(f"\nG-Eval Score Configs ({len(g_eval_configs)}):")
        for config in g_eval_configs:
            print(f"  - {config['name']}: {config['dataType']}")
            if "minValue" in config and "maxValue" in config:
                print(f"    Range: {config['minValue']} - {config['maxValue']}")


async def main() -> None:
    """Main backup execution function."""
    # Get credentials
    public_key, secret_key, host = get_langfuse_credentials()

    print("=" * 70)
    print("Langfuse LLM-as-a-Judge Evaluator Backup")
    print("=" * 70)
    print()

    # Create HTTP client with authentication
    async with httpx.AsyncClient(
        auth=(public_key, secret_key),
        timeout=30.0,
    ) as client:
        # Fetch score configs and prompts
        score_configs = await fetch_score_configs(client, host)
        prompts = await fetch_prompts(client, host)

        # Document evaluator functions
        print("\nDocumenting evaluator functions...")
        evaluator_docs = document_evaluator_functions()
        print(f"Documented {len(evaluator_docs['agent_types'])} agent types")

        # Save backup
        output_path = Path(__file__).parent.parent / "data" / "langfuse_evaluators_backup.json"
        save_backup(score_configs, prompts, evaluator_docs, output_path)

        print("\n" + "=" * 70)
        print("Backup complete!")
        print("=" * 70)
        print()
        print("To restore:")
        print("  1. Score configs: poetry run python scripts/setup_langfuse_score_configs.py")
        print("  2. Prompts: Use Langfuse UI or API to restore prompts")
        print("  3. Evaluators: Already in source code (app/shared/services/g_eval/)")


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
