"""add annotation_queue table

Revision ID: 800137e6a1b1
Revises: 20251218_backfill
Create Date: 2025-12-19 12:10:56.252029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector  # type: ignore[import-untyped]

# revision identifiers, used by Alembic.
revision: str = '800137e6a1b1'
down_revision: Union[str, Sequence[str], None] = '20251218_backfill'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False, comment="Reason for queuing: 'low_quality', 'flagged_by_user', 'negative_feedback'"),
    sa.Column('status', sa.Text(), nullable=False, comment="Status: 'pending', 'reviewed', 'skipped'"),
    sa.Column('queue_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional context: quality_scores, user_id, comments'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_annotation_queue_artifact_status', 'annotation_queue', ['artifact_id', 'status'], unique=False)
    op.create_index('idx_annotation_queue_status_created', 'annotation_queue', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_annotation_queue_artifact_id'), 'annotation_queue', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_annotation_queue_status'), 'annotation_queue', ['status'], unique=False)
    op.create_index(op.f('ix_annotation_queue_trace_id'), 'annotation_queue', ['trace_id'], unique=False)
    op.alter_column('agent_examples', 'output_example',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('agent_examples', 'is_golden',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('agent_examples', 'embedding',
               existing_type=Vector(1536),
               nullable=True)
    op.drop_index(op.f('ix_agent_examples_embedding_ivfflat'), table_name='agent_examples', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_agent_examples_quality'), table_name='agent_examples')
    op.drop_index(op.f('ix_agent_examples_type_quality'), table_name='agent_examples')
    op.create_index(op.f('ix_agent_examples_quality_score'), 'agent_examples', ['quality_score'], unique=False)
    op.alter_column('analyses', 'content_summary',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_analyses_completed'), table_name='analyses', postgresql_where="((status)::text = 'complete'::text)")
    op.drop_index(op.f('ix_analyses_embedding_hnsw'), table_name='analyses', postgresql_ops={'content_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_analyses_search_vector'), table_name='analyses', postgresql_using='gin')
    op.drop_index(op.f('ix_analysis_chunks_content_tsvector'), table_name='analysis_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_analysis_chunks_granularity'), table_name='analysis_chunks')
    op.drop_index(op.f('ix_analysis_chunks_vector_hnsw'), table_name='analysis_chunks', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # Create index if not exists to make migration idempotent
    op.execute('CREATE INDEX IF NOT EXISTS ix_analysis_chunks_hash ON analysis_chunks (hash)')
    op.drop_constraint(op.f('analysis_chunks_analysis_id_fkey'), 'analysis_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_chunks', 'analyses', ['analysis_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_chunks_analysis_id_fkey'), 'analysis_chunks', 'analyses', ['analysis_id'], ['id'])
    # Drop index if exists to make downgrade idempotent
    op.execute('DROP INDEX IF EXISTS ix_analysis_chunks_hash')
    op.create_index(op.f('ix_analysis_chunks_vector_hnsw'), 'analysis_chunks', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_analysis_chunks_granularity'), 'analysis_chunks', ['granularity'], unique=False)
    op.create_index(op.f('ix_analysis_chunks_content_tsvector'), 'analysis_chunks', ['content_tsvector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_analyses_search_vector'), 'analyses', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_analyses_embedding_hnsw'), 'analyses', ['content_embedding'], unique=False, postgresql_ops={'content_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_analyses_completed'), 'analyses', ['created_at'], unique=False, postgresql_where="((status)::text = 'complete'::text)")
    op.alter_column('analyses', 'content_summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_agent_examples_quality_score'), table_name='agent_examples')
    op.create_index(op.f('ix_agent_examples_type_quality'), 'agent_examples', ['agent_type', 'quality_score'], unique=False)
    op.create_index(op.f('ix_agent_examples_quality'), 'agent_examples', ['quality_score'], unique=False)
    op.create_index(op.f('ix_agent_examples_embedding_ivfflat'), 'agent_examples', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('agent_examples', 'embedding',
               existing_type=Vector(1536),
               nullable=False)
    op.alter_column('agent_examples', 'is_golden',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('agent_examples', 'output_example',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_annotation_queue_trace_id'), table_name='annotation_queue')
    op.drop_index(op.f('ix_annotation_queue_status'), table_name='annotation_queue')
    op.drop_index(op.f('ix_annotation_queue_artifact_id'), table_name='annotation_queue')
    op.drop_index('idx_annotation_queue_status_created', table_name='annotation_queue')
    op.drop_index('idx_annotation_queue_artifact_status', table_name='annotation_queue')
    op.drop_table('annotation_queue')
    # ### end Alembic commands ###
