"""Standard error codes for analysis workflow stages.

These error codes are used to classify failures at different stages of the
analysis workflow for debugging, monitoring, and user feedback.
"""

# Agent errors
SECURITY_AUDITOR_FAILED = "SECURITY_AUDITOR_FAILED"
TECH_COMPARATOR_FAILED = "TECH_COMPARATOR_FAILED"
PERFORMANCE_ANALYST_FAILED = "PERFORMANCE_ANALYST_FAILED"
DEPENDENCY_MAPPER_FAILED = "DEPENDENCY_MAPPER_FAILED"
IMPLEMENTATION_PLANNER_FAILED = "IMPLEMENTATION_PLANNER_FAILED"
CODE_QUALITY_CRITIC_FAILED = "CODE_QUALITY_CRITIC_FAILED"
INTEGRATION_FEASIBILITY_FAILED = "INTEGRATION_FEASIBILITY_FAILED"
TREND_VALIDATOR_FAILED = "TREND_VALIDATOR_FAILED"

# Workflow stage errors
EXTRACTION_FAILED = "EXTRACTION_FAILED"
SUPERVISOR_FAILED = "SUPERVISOR_FAILED"
AGGREGATION_FAILED = "AGGREGATION_FAILED"
QUALITY_GATE_FAILED = "QUALITY_GATE_FAILED"
COMPRESSION_FAILED = "COMPRESSION_FAILED"
ARTIFACT_GENERATION_FAILED = "ARTIFACT_GENERATION_FAILED"
EMBEDDING_FAILED = "EMBEDDING_FAILED"

# Agent type to error code mapping
AGENT_ERROR_CODES: dict[str, str] = {
    "security_auditor": SECURITY_AUDITOR_FAILED,
    "tech_comparator": TECH_COMPARATOR_FAILED,
    "performance_analyst": PERFORMANCE_ANALYST_FAILED,
    "dependency_mapper": DEPENDENCY_MAPPER_FAILED,
    "implementation_planner": IMPLEMENTATION_PLANNER_FAILED,
    "code_quality_critic": CODE_QUALITY_CRITIC_FAILED,
    "integration_feasibility": INTEGRATION_FEASIBILITY_FAILED,
    "trend_validator": TREND_VALIDATOR_FAILED,
}
