/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorSessionIdRouteImport } from './routes/tutor.$sessionId'
import { Route as AnalyzeIdRouteImport } from './routes/analyze.$id'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorSessionIdRoute = TutorSessionIdRouteImport.update({
  id: '/tutor/$sessionId',
  path: '/tutor/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeIdRoute = AnalyzeIdRouteImport.update({
  id: '/analyze/$id',
  path: '/analyze/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/showcase': typeof ShowcaseRoute
  '/analyze/$id': typeof AnalyzeIdRoute
  '/tutor/$sessionId': typeof TutorSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/showcase': typeof ShowcaseRoute
  '/analyze/$id': typeof AnalyzeIdRoute
  '/tutor/$sessionId': typeof TutorSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/showcase': typeof ShowcaseRoute
  '/analyze/$id': typeof AnalyzeIdRoute
  '/tutor/$sessionId': typeof TutorSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/showcase'
    | '/analyze/$id'
    | '/tutor/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library' | '/showcase' | '/analyze/$id' | '/tutor/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/showcase'
    | '/analyze/$id'
    | '/tutor/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  ShowcaseRoute: typeof ShowcaseRoute
  AnalyzeIdRoute: typeof AnalyzeIdRoute
  TutorSessionIdRoute: typeof TutorSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/$sessionId': {
      id: '/tutor/$sessionId'
      path: '/tutor/$sessionId'
      fullPath: '/tutor/$sessionId'
      preLoaderRoute: typeof TutorSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/$id': {
      id: '/analyze/$id'
      path: '/analyze/$id'
      fullPath: '/analyze/$id'
      preLoaderRoute: typeof AnalyzeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  ShowcaseRoute: ShowcaseRoute,
  AnalyzeIdRoute: AnalyzeIdRoute,
  TutorSessionIdRoute: TutorSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
