/* eslint-disable max-lines -- Mock factories require comprehensive data definitions */
/**
 * Mock Data Factories for MSW
 *
 * Issue #551: MSW for Network-Level API Mocking
 *
 * Provides factory functions to generate consistent mock data
 * for API responses. Uses Zod types for type safety.
 *
 * @module mocks/factories
 */

import type {
  Analysis,
  AnalysisProgressResponse,
  AnalysisStatusResponse,
  AnalyzeResponse,
  ArtifactMetadataResponse,
  HealthCheckResponse,
  LibraryListResponse,
} from '@/schemas/api'

/**
 * Generate a valid UUID for mock data
 */
export function mockUUID(): string {
  return crypto.randomUUID()
}

/**
 * Generate a mock AnalyzeResponse (POST /api/v1/analyze)
 */
export function mockAnalyzeResponse(overrides?: Partial<AnalyzeResponse>): AnalyzeResponse {
  const analysisId = overrides?.analysis_id ?? mockUUID()
  return {
    analysis_id: analysisId,
    sse_endpoint: `/api/v1/analyze/${analysisId}/stream`,
    status: 'pending',
    url: 'https://example.com/article',
    content_type: 'article',
    ...overrides,
  }
}

/**
 * Generate a mock AnalysisStatusResponse (GET /api/v1/analyze/{id})
 */
export function mockAnalysisStatus(
  overrides?: Partial<AnalysisStatusResponse>
): AnalysisStatusResponse {
  return {
    status: 'complete',
    artifact_id: mockUUID(),
    ...overrides,
  }
}

/**
 * Generate a mock ArtifactMetadataResponse
 */
export function mockArtifact(
  overrides?: Partial<ArtifactMetadataResponse>
): ArtifactMetadataResponse {
  return {
    analysis_id: mockUUID(),
    artifact_id: mockUUID(),
    markdown_content: `# Implementation Guide

## Overview
This is a comprehensive implementation guide generated by SkillForge.

## Key Concepts
- Concept 1: Important foundational knowledge
- Concept 2: Advanced techniques
- Concept 3: Best practices

## Code Examples
\`\`\`typescript
function example() {
  return 'Hello, World!'
}
\`\`\`

## Summary
This guide provides a solid foundation for implementation.
`,
    metadata: {},
    created_at: new Date().toISOString(),
    ...overrides,
  }
}

/**
 * Generate a mock Analysis object (for list endpoints)
 */
export function mockAnalysis(overrides?: Partial<Analysis>): Analysis {
  return {
    id: mockUUID(),
    url: 'https://example.com/article',
    content_type: 'article',
    title: 'Sample Technical Article',
    status: 'complete',
    created_at: new Date().toISOString(),
    artifact_id: mockUUID(),
    ...overrides,
  }
}

/**
 * Generate a list of mock analyses
 */
export function mockAnalysisList(count = 5): Analysis[] {
  return Array.from({ length: count }, (_, i) =>
    mockAnalysis({
      title: `Analysis ${i + 1}`,
      created_at: new Date(Date.now() - i * 24 * 60 * 60 * 1000).toISOString(),
    })
  )
}

/**
 * Generate mock progress events for an analysis
 */
export function mockAnalysisProgress(analysisId: string): AnalysisProgressResponse {
  const baseTime = Date.now()
  return {
    analysis_id: analysisId,
    events: [
      {
        stage: 'extraction',
        status: 'complete',
        progress_data: { word_count: 2500 },
        timestamp: new Date(baseTime - 60000).toISOString(),
      },
      {
        stage: 'analysis',
        status: 'complete',
        progress_data: { insights_count: 12 },
        timestamp: new Date(baseTime - 30000).toISOString(),
      },
      {
        stage: 'artifact_generation',
        status: 'complete',
        progress_data: { markdown_length: 5000 },
        timestamp: new Date(baseTime).toISOString(),
      },
    ],
  }
}

/**
 * Generate mock SSE events for streaming
 */
export function mockSSEEvents(analysisId: string): Array<Record<string, unknown>> {
  return [
    {
      type: 'progress',
      analysis_id: analysisId,
      stage: 'extraction',
      status: 'running',
      timestamp: new Date().toISOString(),
    },
    {
      type: 'progress',
      analysis_id: analysisId,
      stage: 'extraction',
      status: 'complete',
      timestamp: new Date().toISOString(),
      details: { word_count: 2500 },
    },
    {
      type: 'progress',
      analysis_id: analysisId,
      stage: 'analysis',
      status: 'running',
      timestamp: new Date().toISOString(),
    },
    {
      type: 'progress',
      analysis_id: analysisId,
      stage: 'analysis',
      status: 'complete',
      timestamp: new Date().toISOString(),
    },
    {
      type: 'complete',
      analysis_id: analysisId,
      stage: 'workflow',
      status: 'complete',
      timestamp: new Date().toISOString(),
      artifact_id: mockUUID(),
    },
  ]
}

/**
 * Generate mock health check response
 */
export function mockHealthCheck(overrides?: Partial<HealthCheckResponse>): HealthCheckResponse {
  return {
    status: 'healthy',
    version: '1.0.0',
    environment: 'development',
    database: { status: 'connected' },
    ...overrides,
  }
}

/**
 * Generate mock library list response
 */
export function mockLibraryList(overrides?: Partial<LibraryListResponse>): LibraryListResponse {
  return {
    items: [
      {
        analysis_id: mockUUID(),
        url: 'https://example.com/article1',
        title: 'Understanding RAG Architecture',
        content_type: 'article',
        status: 'complete',
        tags: ['rag', 'ai', 'architecture'],
        snippet: 'A deep dive into Retrieval-Augmented Generation...',
        rank: 0.95,
        created_at: new Date().toISOString(),
      },
      {
        analysis_id: mockUUID(),
        url: 'https://example.com/article2',
        title: 'Building LangGraph Workflows',
        content_type: 'article',
        status: 'complete',
        tags: ['langgraph', 'workflows', 'agents'],
        snippet: 'How to create multi-agent workflows with LangGraph...',
        rank: 0.88,
        created_at: new Date().toISOString(),
      },
    ],
    total: 2,
    limit: 20,
    offset: 0,
    ...overrides,
  }
}
